import "./components/swipers";
import "./components/tooltip";
import "./components/dropdown";
import "./components/rating-more-btn";
import "./components/form-validation";
import "./components/smoothScroll";
import "./components/range-slider";
import "./components/product-modal";
import "./components/product-modal-slider";
import "./components/map";
import "./components/catalog-tags"
import "./components/filter-dropdown"
import "./components/filter-more-btn"
